# Site settings 
title_left    : "Cyber"
title_right   : "JUG" # default: ""
description   : "Eine Online Java User Group"
keywords      : "CyberJUG, Java User Group, digital, cyber, java"
url           : "https://cyberjug.de" # site url
baseurl       : ""
cover         : "/assets/images/logo_16-9.png"
future        : true # show posts that are in the future

# collections
collections:
  news:
    directory: past
    output: true
    permalink: aktuelles/:year-:month-:day-:title/
  upcoming:
    directory: upcoming
    output: true
    permalink: vortrag/:title/
  past:
    directory: past
    output: true
    permalink: vortrag/:title/

# google_analytics  : UA-XXXXX-XX
twitter_username  : "cyberjug"
postshare_enabled : true

# Build settings
markdown    : kramdown
highlighter : rouge

# Sass configuration
sass:
  sass_dir  : assets/scss
  style     : expanded

# Author settings
author:
  name     : "Die Orga der CyberJUG"

plugins:
  - jekyll-sitemap
  - bourbon
  - jekyll-paginate
  - jekyll-tidy
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from
  
feed:
  collections:
    - news
    - upcoming
    - past

# set up HTML beautifier
jekyll_tidy:
  compress_html: false

# navbar pages
navbar:
  - slug : aktuelles
    title: Aktuelles
  - slug : ueber
    title: Über
  - slug: mitmachen
    title: Mitmachen!
  - slug : kontakt
    title: Kontakt

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md", "script", "vendor", cyberjug.gemspec]
